### ISSUE TITLE
error di kwitansi di tab yang sudah confirm

### ISSUE THREAD

**Issue by yusufsopyan** [CozzalIT/gitTransaksiCozzal#4]
![Screen Shot 2018-04-14 at 9:01 PM](http://marker.screenshots.prod.s3.amazonaws.com/2645bbfbb0b14881a45ad5c85794e929-1523739694979.png)

detail format kwitansi bisa lihat di kwitansi dp.

---
### More Info

**Source URL**: [http://transaksi.cozzal.com/view/superadmin/transaksi/kwitansi.php?kwitansi=274](http://transaksi.cozzal.com/view/superadmin/transaksi/kwitansi.php?kwitansi=274)

<table><tr><td><strong>Browser</strong></td><td>Chrome 65.0.3325.181</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 744</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36</td></tr></table>

**Comment by CozzalIT** [comment]
Solve
