### ISSUE TITLE
pdf.php

### ISSUE THREAD

**Issue by yusufsopyan** [CozzalIT/gitTransaksiCozzal#6]
![Screen Shot 2018-04-15 at 1:30 PM](http://marker.screenshots.prod.s3.amazonaws.com/83a86a6d48dd412ebed60cc8c6774478-1523799048213.png)
---
### More Info

**Source URL**: [http://transaksi.cozzal.com/view/superadmin/transaksi/pdf.php?kwitansi=241](http://transaksi.cozzal.com/view/superadmin/transaksi/pdf.php?kwitansi=241)

<table><tr><td><strong>Browser</strong></td><td>Chrome 65.0.3325.181</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 744</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36</td></tr></table>

**Comment by CozzalIT** [comment]
Untuk unit yang detail lantai nya belum di input defaultnya jadi "-"
