### ISSUE TITLE
harga owner disesuaikan dengan harga owner saat itu, tidak ikut berubah untuk transaksi lama

### ISSUE THREAD

**Issue by yusufsopyan** [CozzalIT/gitTransaksiCozzal#7]
![Screen Shot 2018-04-15 at 1:35 PM](http://marker.screenshots.prod.s3.amazonaws.com/83771fdf5121429fb90797caa679b62e-1523799355418.png)
---
### More Info

**Source URL**: [http://transaksi.cozzal.com/view/superadmin/owner/detail_payment.php?detail=268a273x](http://transaksi.cozzal.com/view/superadmin/owner/detail_payment.php?detail=268a273x)

<table><tr><td><strong>Browser</strong></td><td>Chrome 65.0.3325.181</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 744</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36</td></tr></table>

**Comment by CozzalIT** [comment]
Solve
